# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import qapi_pb2 as qapi__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in qapi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class QapiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sink = channel.stream_unary(
                '/Qapi.Qapi/Sink',
                request_serializer=qapi__pb2.Chunk.SerializeToString,
                response_deserializer=qapi__pb2.SinkResult.FromString,
                _registered_method=True)
        self.Source = channel.unary_stream(
                '/Qapi.Qapi/Source',
                request_serializer=qapi__pb2.SourceRequest.SerializeToString,
                response_deserializer=qapi__pb2.Chunk.FromString,
                _registered_method=True)
        self.SayHello = channel.unary_stream(
                '/Qapi.Qapi/SayHello',
                request_serializer=qapi__pb2.HelloRequest.SerializeToString,
                response_deserializer=qapi__pb2.HelloReply.FromString,
                _registered_method=True)


class QapiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sink(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Source(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QapiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sink': grpc.stream_unary_rpc_method_handler(
                    servicer.Sink,
                    request_deserializer=qapi__pb2.Chunk.FromString,
                    response_serializer=qapi__pb2.SinkResult.SerializeToString,
            ),
            'Source': grpc.unary_stream_rpc_method_handler(
                    servicer.Source,
                    request_deserializer=qapi__pb2.SourceRequest.FromString,
                    response_serializer=qapi__pb2.Chunk.SerializeToString,
            ),
            'SayHello': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=qapi__pb2.HelloRequest.FromString,
                    response_serializer=qapi__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Qapi.Qapi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Qapi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sink(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Qapi.Qapi/Sink',
            qapi__pb2.Chunk.SerializeToString,
            qapi__pb2.SinkResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Source(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Qapi.Qapi/Source',
            qapi__pb2.SourceRequest.SerializeToString,
            qapi__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Qapi.Qapi/SayHello',
            qapi__pb2.HelloRequest.SerializeToString,
            qapi__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
