# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qapi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nqapi.proto\x12\x04Qapi\x1a\x19google/protobuf/any.proto\"(\n\x14InputEntryDescriptor\x12\x10\n\x08streamId\x18\x01 \x01(\t\")\n\x15OutputEntryDescriptor\x12\x10\n\x08streamId\x18\x01 \x01(\t\"@\n\x05\x43hunk\x12\x12\n\nexpression\x18\x01 \x01(\t\x12#\n\x05\x62ytes\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"#\n\rSourceRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\"\x0c\n\nSinkResult\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x95\x01\n\x04Qapi\x12)\n\x04Sink\x12\x0b.Qapi.Chunk\x1a\x10.Qapi.SinkResult\"\x00(\x01\x12.\n\x06Source\x12\x13.Qapi.SourceRequest\x1a\x0b.Qapi.Chunk\"\x00\x30\x01\x12\x32\n\x08SayHello\x12\x12.Qapi.HelloRequest\x1a\x10.Qapi.HelloReply0\x01\x42\r\xaa\x02\nTdip.Qapiob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qapi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\nTdip.Qapio'
  _globals['_INPUTENTRYDESCRIPTOR']._serialized_start=47
  _globals['_INPUTENTRYDESCRIPTOR']._serialized_end=87
  _globals['_OUTPUTENTRYDESCRIPTOR']._serialized_start=89
  _globals['_OUTPUTENTRYDESCRIPTOR']._serialized_end=130
  _globals['_CHUNK']._serialized_start=132
  _globals['_CHUNK']._serialized_end=196
  _globals['_SOURCEREQUEST']._serialized_start=198
  _globals['_SOURCEREQUEST']._serialized_end=233
  _globals['_SINKRESULT']._serialized_start=235
  _globals['_SINKRESULT']._serialized_end=247
  _globals['_HELLOREQUEST']._serialized_start=249
  _globals['_HELLOREQUEST']._serialized_end=277
  _globals['_HELLOREPLY']._serialized_start=279
  _globals['_HELLOREPLY']._serialized_end=308
  _globals['_QAPI']._serialized_start=311
  _globals['_QAPI']._serialized_end=460
# @@protoc_insertion_point(module_scope)
